<?php

declare(strict_types=1);

namespace PhpSoftBox\TestUtils\Tests\Database\Reset;

use PDO;
use PhpSoftBox\TestUtils\Database\Reset\PostgresResetDriver;
use PhpSoftBox\TestUtils\Database\ResetReloadStrategy;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;

/**
 * БД — сервис docker-compose, пользователь — суперпользователь из POSTGRES_USER; переопределение: TEST_UTILS_POSTGRES_DSN.
 */
#[CoversClass(ResetReloadStrategy::class)]
#[CoversClass(PostgresResetDriver::class)]
#[CoversMethod(ResetReloadStrategy::class, 'reload')]
final class ResetReloadStrategyPostgresIntegrationTest extends AbstractResetIntegrationTestCase
{
    protected function dsnEnvironmentVariable(): string
    {
        return 'TEST_UTILS_POSTGRES_DSN';
    }

    protected function defaultDsn(): string
    {
        return 'postgres://phpsoftbox:phpsoftbox@postgres:5432/psb_test_utils_reset';
    }

    protected function schemaDump(): string
    {
        // Несистемная схема billing, serial, identity и последовательность, не принадлежащая таблице.
        return <<<'SQL'
            -- PostgreSQL database dump
            CREATE SCHEMA billing;
            CREATE TABLE public.parents (id bigserial PRIMARY KEY);
            CREATE TABLE billing.children (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                parent_id bigint NOT NULL REFERENCES public.parents (id)
            );
            CREATE TABLE public.tags (code text PRIMARY KEY);
            CREATE SEQUENCE public.standalone_seq START WITH 100;
            -- PostgreSQL database dump complete

            SQL;
    }

    protected function insertRelatedRows(PDO $pdo): void
    {
        $pdo->exec(
            '
                INSERT INTO public.parents DEFAULT
                VALUES
            ',
        );
        $pdo->exec(
            '
                INSERT INTO billing.children (parent_id)
                SELECT id
                FROM public.parents
            ',
        );
        $pdo->exec(
            '
                INSERT INTO public.tags (code)
                VALUES (\'a\')
            ',
        );
        $pdo->query("
            SELECT nextval('public.standalone_seq')
        ");
    }

    protected function insertAndDeleteRow(PDO $pdo): void
    {
        $pdo->exec(
            '
                INSERT INTO public.parents DEFAULT
                VALUES
            ',
        );
        $pdo->exec(
            '
                DELETE FROM public.parents
            ',
        );
    }

    protected function counters(PDO $pdo): array
    {
        $rows = $pdo->query(
            '
                SELECT schemaname || \'.\' || sequencename AS name, last_value
                FROM pg_sequences
                ORDER BY 1
            ',
        )->fetchAll(PDO::FETCH_KEY_PAIR);

        $counters = [];
        foreach ($rows as $sequence => $value) {
            $counters[(string) $sequence] = $value === null ? null : (int) $value;
        }

        return $counters;
    }

    protected function rowCount(PDO $pdo): int
    {
        return (int) $pdo->query(
            '
                SELECT (
                    SELECT COUNT(*)
                    FROM public.parents
                ) + (
                    SELECT COUNT(*)
                    FROM billing.children
                ) + (
                    SELECT COUNT(*)
                    FROM public.tags
                )
            ',
        )->fetchColumn();
    }
}
